"""initial_schema

Revision ID: 87feb44ecf54
Revises:
Create Date: 2026-08-08 11:15:10.050100
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "87feb44ecf54"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "campuses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("business_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_campuses_business_id"), "campuses", ["business_id"], unique=True)
    op.create_table(
        "integration_syncs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("resource", sa.String(length=40), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("records_read", sa.Integer(), nullable=False),
        sa.Column("records_written", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.String(length=80), nullable=True),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False)
    op.create_table(
        "class_groups",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campus_id", sa.String(length=36), nullable=False),
        sa.Column("business_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("grade", sa.String(length=50), nullable=False),
        sa.Column("subject", sa.String(length=80), nullable=False),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column("priority", sa.String(length=30), nullable=False),
        sa.Column("required_devices", sa.JSON(), nullable=False),
        sa.Column("teacher_business_id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campus_id", "business_id"),
    )
    op.create_index(
        op.f("ix_class_groups_business_id"), "class_groups", ["business_id"], unique=False
    )
    op.create_index(op.f("ix_class_groups_campus_id"), "class_groups", ["campus_id"], unique=False)
    op.create_table(
        "course_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campus_id", sa.String(length=36), nullable=False),
        sa.Column("business_id", sa.String(length=50), nullable=False),
        sa.Column("class_business_id", sa.String(length=40), nullable=False),
        sa.Column("teacher_business_id", sa.String(length=40), nullable=False),
        sa.Column("subject", sa.String(length=80), nullable=False),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column("required_devices", sa.JSON(), nullable=False),
        sa.Column("duration_minutes", sa.Integer(), nullable=False),
        sa.Column("suggested_slot_id", sa.String(length=40), nullable=True),
        sa.Column("is_locked", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campus_id", "business_id"),
    )
    op.create_index(
        op.f("ix_course_sessions_business_id"), "course_sessions", ["business_id"], unique=False
    )
    op.create_index(
        op.f("ix_course_sessions_campus_id"), "course_sessions", ["campus_id"], unique=False
    )
    op.create_table(
        "data_snapshots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_data_snapshots_checksum"), "data_snapshots", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_data_snapshots_revision"), "data_snapshots", ["revision"], unique=False
    )
    op.create_table(
        "rooms",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campus_id", sa.String(length=36), nullable=False),
        sa.Column("business_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("devices", sa.JSON(), nullable=False),
        sa.Column("available_slot_ids", sa.JSON(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campus_id", "business_id"),
    )
    op.create_index(op.f("ix_rooms_business_id"), "rooms", ["business_id"], unique=False)
    op.create_index(op.f("ix_rooms_campus_id"), "rooms", ["campus_id"], unique=False)
    op.create_table(
        "rules",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("business_id", sa.String(length=50), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_ids", sa.JSON(), nullable=False),
        sa.Column("constraint_type", sa.String(length=60), nullable=False),
        sa.Column("scope", sa.JSON(), nullable=False),
        sa.Column("hardness", sa.String(length=10), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=True),
        sa.Column("structured_expression", sa.JSON(), nullable=False),
        sa.Column("source_doc", sa.String(length=255), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_rules_business_id"), "rules", ["business_id"], unique=True)
    op.create_table(
        "teachers",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campus_id", sa.String(length=36), nullable=False),
        sa.Column("business_id", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("subject", sa.String(length=80), nullable=False),
        sa.Column("max_hours", sa.Integer(), nullable=False),
        sa.Column("unavailable_slot_ids", sa.JSON(), nullable=False),
        sa.Column("preferred_slot_ids", sa.JSON(), nullable=False),
        sa.Column("data_level", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campus_id", "business_id"),
    )
    op.create_index(op.f("ix_teachers_business_id"), "teachers", ["business_id"], unique=False)
    op.create_index(op.f("ix_teachers_campus_id"), "teachers", ["campus_id"], unique=False)
    op.create_table(
        "time_slots",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("campus_id", sa.String(length=36), nullable=False),
        sa.Column("business_id", sa.String(length=40), nullable=False),
        sa.Column("weekday", sa.String(length=20), nullable=False),
        sa.Column("start_time", sa.String(length=10), nullable=False),
        sa.Column("end_time", sa.String(length=10), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["campus_id"],
            ["campuses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("campus_id", "business_id"),
    )
    op.create_index(op.f("ix_time_slots_business_id"), "time_slots", ["business_id"], unique=False)
    op.create_index(op.f("ix_time_slots_campus_id"), "time_slots", ["campus_id"], unique=False)
    op.create_table(
        "solver_runs",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("run_type", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("model_status", sa.String(length=30), nullable=True),
        sa.Column("request_payload", sa.JSON(), nullable=False),
        sa.Column("result_payload", sa.JSON(), nullable=False),
        sa.Column("objective_value", sa.Float(), nullable=True),
        sa.Column("best_bound", sa.Float(), nullable=True),
        sa.Column("wall_time_seconds", sa.Float(), nullable=True),
        sa.Column("conflict_rule_ids", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["data_snapshots.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_solver_runs_status"), "solver_runs", ["status"], unique=False)
    op.create_table(
        "schedule_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("version_no", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("solver_run_id", sa.String(length=36), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("approved_by", sa.String(length=36), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["approved_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["schedule_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solver_run_id"],
            ["solver_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("solver_run_id"),
    )
    op.create_index(
        op.f("ix_schedule_versions_version_no"), "schedule_versions", ["version_no"], unique=True
    )
    op.create_table(
        "reschedule_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("parent_schedule_id", sa.String(length=36), nullable=False),
        sa.Column("solver_run_id", sa.String(length=36), nullable=True),
        sa.Column("candidate_schedule_id", sa.String(length=36), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_schedule_id"],
            ["schedule_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_schedule_id"],
            ["schedule_versions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["solver_run_id"],
            ["solver_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_assignments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("schedule_version_id", sa.String(length=36), nullable=False),
        sa.Column("course_session_id", sa.String(length=36), nullable=False),
        sa.Column("slot_business_id", sa.String(length=40), nullable=False),
        sa.Column("room_business_id", sa.String(length=40), nullable=False),
        sa.Column("change_kind", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_session_id"],
            ["course_sessions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_version_id"],
            ["schedule_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("schedule_version_id", "course_session_id"),
    )
    op.create_index(
        op.f("ix_schedule_assignments_schedule_version_id"),
        "schedule_assignments",
        ["schedule_version_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_schedule_assignments_schedule_version_id"), table_name="schedule_assignments"
    )
    op.drop_table("schedule_assignments")
    op.drop_table("reschedule_events")
    op.drop_index(op.f("ix_schedule_versions_version_no"), table_name="schedule_versions")
    op.drop_table("schedule_versions")
    op.drop_index(op.f("ix_solver_runs_status"), table_name="solver_runs")
    op.drop_table("solver_runs")
    op.drop_index(op.f("ix_time_slots_campus_id"), table_name="time_slots")
    op.drop_index(op.f("ix_time_slots_business_id"), table_name="time_slots")
    op.drop_table("time_slots")
    op.drop_index(op.f("ix_teachers_campus_id"), table_name="teachers")
    op.drop_index(op.f("ix_teachers_business_id"), table_name="teachers")
    op.drop_table("teachers")
    op.drop_index(op.f("ix_rules_business_id"), table_name="rules")
    op.drop_table("rules")
    op.drop_index(op.f("ix_rooms_campus_id"), table_name="rooms")
    op.drop_index(op.f("ix_rooms_business_id"), table_name="rooms")
    op.drop_table("rooms")
    op.drop_index(op.f("ix_data_snapshots_revision"), table_name="data_snapshots")
    op.drop_index(op.f("ix_data_snapshots_checksum"), table_name="data_snapshots")
    op.drop_table("data_snapshots")
    op.drop_index(op.f("ix_course_sessions_campus_id"), table_name="course_sessions")
    op.drop_index(op.f("ix_course_sessions_business_id"), table_name="course_sessions")
    op.drop_table("course_sessions")
    op.drop_index(op.f("ix_class_groups_campus_id"), table_name="class_groups")
    op.drop_index(op.f("ix_class_groups_business_id"), table_name="class_groups")
    op.drop_table("class_groups")
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("integration_syncs")
    op.drop_index(op.f("ix_campuses_business_id"), table_name="campuses")
    op.drop_table("campuses")
    # ### end Alembic commands ###
