import { useQueryClient } from "@tanstack/react-query";
import { Activity, Play, SlidersHorizontal } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";

import { getListSchedulesApiV1SchedulesGetQueryKey, getListSolverRunsApiV1SolverRunsGetQueryKey, getOverviewApiV1OverviewGetQueryKey, useGetSolverRunApiV1SolverRunsRunIdGet, useListRulesApiV1RulesGet, useListSolverRunsApiV1SolverRunsGet, useSubmitSolverRunApiV1SolverRunsPost } from "@/api/generated/client";
import { type SolverRunResponse } from "@/api/generated/models";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ErrorState, LoadingState, PageHeader } from "@/components/page";
import { errorMessage } from "@/lib/format";
import { modelStatusLabel, statusLabel } from "@/lib/labels";
import { statusTone } from "@/lib/status";

export function SolverPage() {
  const client = useQueryClient(); const [preferenceWeight, setPreferenceWeight] = useState(100); const [runId, setRunId] = useState(""); const [current, setCurrent] = useState<SolverRunResponse | null>(null);
  const rules = useListRulesApiV1RulesGet({ status: "active" }); const runs = useListSolverRunsApiV1SolverRunsGet({ query: { refetchInterval: 5000 } });
  const progress = useGetSolverRunApiV1SolverRunsRunIdGet(runId, { query: { enabled: Boolean(runId), refetchInterval: (query) => query.state.data?.status === "completed" || query.state.data?.status === "failed" ? false : 700 } });
  const submit = useSubmitSolverRunApiV1SolverRunsPost({ mutation: { onSuccess: (result) => { setRunId(result.id); setCurrent(result); toast.success("求解任务已创建"); }, onError: (error) => toast.error(errorMessage(error)) } });
  useEffect(() => { if (progress.data) { setCurrent(progress.data); if (progress.data.status === "completed" || progress.data.status === "failed") { void Promise.all([client.invalidateQueries({ queryKey: getListSchedulesApiV1SchedulesGetQueryKey() }), client.invalidateQueries({ queryKey: getListSolverRunsApiV1SolverRunsGetQueryKey() }), client.invalidateQueries({ queryKey: getOverviewApiV1OverviewGetQueryKey() })]); } } }, [client, progress.data]);
  if (rules.isPending || runs.isPending) return <LoadingState />;
  if (rules.isError || runs.isError) return <ErrorState retry={() => { void rules.refetch(); void runs.refetch(); }} />;
  const activeRun = current ?? runs.data?.[0] ?? null;
  return <div className="space-y-5"><PageHeader title="排课求解" actions={<Badge tone="blue">已启用规则 {rules.data?.length ?? 0}</Badge>} /><div className="grid gap-2 xl:grid-cols-[360px_minmax(0,1fr)]"><section className="border border-zinc-200 bg-white p-5"><div className="flex items-center gap-2"><SlidersHorizontal className="size-4 text-blue-600" /><h2 className="font-semibold">目标权重</h2></div><label className="mt-6 block text-sm text-zinc-700">教师偏好 <span className="float-right font-mono text-zinc-500">{preferenceWeight}</span><input className="mt-3 w-full accent-blue-600" type="range" min="0" max="300" step="10" value={preferenceWeight} onChange={(event) => setPreferenceWeight(Number(event.target.value))} /></label><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="border-l-2 border-zinc-300 pl-3"><div className="text-xs text-zinc-400">座位浪费</div><div className="mt-1">1</div></div><div className="border-l-2 border-zinc-300 pl-3"><div className="text-xs text-zinc-400">最小变更</div><div className="mt-1">100000</div></div></div><Button className="mt-7 w-full" onClick={() => submit.mutate({ data: { time_limit_seconds: 30, preference_weight: preferenceWeight, seat_waste_weight: 1, change_weight: 100000, wait: false } })} disabled={submit.isPending || activeRun?.status === "running"}><Play className="size-4" />开始求解</Button></section><RunPanel run={activeRun} /></div><section className="border border-zinc-200 bg-white"><div className="border-b border-zinc-200 px-4 py-3 text-sm font-semibold">求解记录</div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-zinc-50 text-xs text-zinc-500"><tr><th className="h-9 px-4">任务</th><th>状态</th><th>模型结果</th><th>目标值</th><th>最佳界</th><th>耗时</th></tr></thead><tbody>{runs.data?.map((run) => <tr key={run.id} className="border-t border-zinc-100"><td className="h-10 px-4 font-mono text-xs">{run.id.slice(0, 8)}</td><td><Badge tone={statusTone(run.status)}>{statusLabel(run.status)}</Badge></td><td>{modelStatusLabel(run.model_status)}</td><td>{run.objective_value?.toFixed(1) ?? "-"}</td><td>{run.best_bound?.toFixed(1) ?? "-"}</td><td>{run.wall_time_seconds?.toFixed(2) ?? "-"} 秒</td></tr>)}</tbody></table></div></section></div>;
}

function RunPanel({ run }: { run: SolverRunResponse | null }) { return <section className="border border-zinc-200 bg-white p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Activity className="size-4 text-blue-600" /><h2 className="font-semibold">实时状态</h2></div><Badge tone={statusTone(run?.status)}>{statusLabel(run?.status) ?? "待启动"}</Badge></div><div className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Value label="模型状态" value={modelStatusLabel(run?.model_status)} /><Value label="目标函数值" value={run?.objective_value?.toFixed(1) ?? "-"} /><Value label="最佳界" value={run?.best_bound?.toFixed(1) ?? "-"} /><Value label="耗时" value={run?.wall_time_seconds ? `${run.wall_time_seconds.toFixed(2)} 秒` : "-"} /></div>{run?.model_status === "INFEASIBLE" ? <div className="mt-6 border-l-2 border-red-600 bg-red-50 px-4 py-3 text-sm text-red-800">冲突规则：{run.conflict_rule_ids.join("、") || "模型未返回可追溯规则"}</div> : null}{run?.priority_explanations?.length ? <div className="mt-4 border-l-2 border-amber-500 bg-amber-50 px-4 py-3 text-sm text-amber-900">{run.priority_explanations[0]}</div> : null}{run?.error_message ? <div className="mt-4 text-sm text-red-700">{run.error_message}</div> : null}</section>; }
function Value({ label, value }: { label: string; value: string }) { return <div><div className="text-xs text-zinc-400">{label}</div><div className="mt-1 font-mono text-sm text-zinc-800">{value}</div></div>; }
